name: Workflow Name
on: [push]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    # step 1
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Greeting Message 
      run: echo "Hello, world"
