name: Autocoder Bot Workflow

on: 
  issues:
    types: [opened, reopened, labeled]
env:
    ISSUE_TITLE: ${{ github.event.issue.title }}
    ISSUE_NUMBER: ${{ github.event.issue.number }}
    ISSUE_BODY: ${{ github.event.issue.body }}
    ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
    ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}

    REPO_NAME: ${{github.repository}}
    # ISSUE_NUM: ${{github.event.issue.number}}
    OPENAI_API_KEY: ${{secrets.OPENAI_KEY}}
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


jobs:
  
  process_issue:
    runs-on: ubuntu-latest
    # timeout-minutes: 5
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout repository for Process Issue
        uses: actions/checkout@v4

      - name: Make script executable
        run: |
         chmod +x ./scripts/script.sh

      - name: run_the_script
        run: ./scripts.script.sh

      - name: Validate issue information
        id: validate
        run: |
          # Fail if required information is missing
          if [ -z "$ISSUE_BODY" ]; then
            echo "Error: Issue body is empty"
            exit 1
          fi
          # Output issue information for logging
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_OUTPUT
          echo "has_required_label=${{ contains(env.ISSUE_LABELS, 'autocoder-bot') }}" >> $GITHUB_OUTPUT
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-bot/
          if-no-files-found: error
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact/
      
      - name: List files recursively
        run: ls -R ./autocoder-artifact/

  