name: Access Issue Information
on:
  issues:
    types: [opened, reopened]
env:
    ISSUE_TITLE: ${{ github.event.issue.title }}
    ISSUE_NUMBER: ${{ github.event.issue.number }}
    ISSUE_BODY: ${{ github.event.issue.body }}
    ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
    ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}

    REPO_NAME: ${{github.repository}}
    # ISSUE_NUM: ${{github.event.issue.number}}
    OPENAI_API_KEY: ${{secrets.OPENAI_KEY}}
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  access_issue_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions 
        uses: actions/checkout@v4

      - name: Print Issue Information  
        run: |
          echo "Issue Title: ${ISSUE_TITLE}"
          echo "Issue Number: ${ISSUE_NUMBER}"     
          echo "Issue Body: ${ISSUE_BODY}"     
          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"     
          echo "Issue Labels: ${ISSUE_LABELS}"
          echo "Issue repo name: ${REPO_NAME}"


  code_generation:
    runs-on: ubuntu-latest
    outputs:
      label_status: ${{ env.LABEL_EXISTS }}
    steps:
      - name: Set env variables
        run: |
          echo "REPO NAME: ${REPO_NAME}"
          echo "ISSUE NUM: ${ISSUE_NUMBER}"
          echo "GITHUB TOKEN: ${GITHUB_TOKEN}"
          echo "OPENAI API KEY: ${OPENAI_API_KEY}"

      - name: Label exists env variable    
        if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
        run: |
         echo "Label 'autocoder-bot' exists..."
         echo "LABEL_EXISTS=true" >> $GITHUB_ENV 

       # Add else condition to set false
      - name: Label doesn't exist env variable
        if: ${{ !contains(github.event.issue.labels.*.name, 'autocoder-bot') }}
        run: |
          echo "Label 'autocoder-bot' does not exist..."
          echo "LABEL_EXISTS=false" >> $GITHUB_ENV   

  autocode_bot_code_gen:
    needs: code_generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ needs.code_generation.outputs.label_status }}
        uses: actions/checkout@v4

      - name: Run gpt interaction script
        if: ${{ needs.code_generation.outputs.label_status }}
        run: |
          chmod u+x ./scripts/hello.bash
          bash ./scripts/hello.bash 
#          # chmod u+x ./scripts/gpt_interaction_script.sh
#          # bash ./scripts/gpt_interaction_script.sh 



